export const Ldslider = [
	{
	  image:
      'https://c4.wallpaperflare.com/wallpaper/100/708/978/bmw-320d-car-msport-wallpaper-preview.jpg'
	},
	{
        image:
        'https://c4.wallpaperflare.com/wallpaper/275/1023/603/car-car-interior-gear-shifter-bmw-wallpaper-preview.jpg'
	},
	{
	  image:
        'https://c0.wallpaperflare.com/preview/931/417/317/black-bmw-vehicle-steering-wheel.jpg'
	},
	{
		image:
         'https://wallpapercave.com/wp/wp4258090.jpg'
	},
	{
		image:
		'https://wallpapercave.com/w/wp11459734'
	},
	{
		image:
        'https://wallpapercave.com/dwp1x/wp11459745.jpg'
	},
    {
        image:
        'https://wallpapercave.com/wp/wp5539959.jpg'
	}
	
];